owner: LoopedSEO1
repo: loopedseo-status
sites:
  - name: LoopedSEO API
    url: https://api.loopedseo.com/health
  - name: LoopedSEO App
    url: https://app.loopedseo.com
status-website:
  cname: status.loopedseo.com
  name: LoopedSEO Status
  theme: light
